// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ8dIhZ1tOrjKRFY0m3ji17m4dzxXERBg',
    appId: '1:636826174032:web:2d9f5a7f06cc68b7b08755',
    messagingSenderId: '636826174032',
    projectId: 'fir-series-75010',
    authDomain: 'fir-series-75010.firebaseapp.com',
    storageBucket: 'fir-series-75010.appspot.com',
    measurementId: 'G-BPCVH3LHVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzDT8i_jSX1kxgNHL9E83TEM3im6WDjJg',
    appId: '1:636826174032:android:6af7405f2e7af08ab08755',
    messagingSenderId: '636826174032',
    projectId: 'fir-series-75010',
    storageBucket: 'fir-series-75010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7pCzPcscXJQwdVhqJpvZB8S8EF5sxORc',
    appId: '1:636826174032:ios:89e4557de643e369b08755',
    messagingSenderId: '636826174032',
    projectId: 'fir-series-75010',
    storageBucket: 'fir-series-75010.appspot.com',
    androidClientId: '636826174032-5robrsihrm0p0i5q5g78o7tstnt2hlbj.apps.googleusercontent.com',
    iosClientId: '636826174032-i7qcu64fcd8igdls5rtj83cjeunkgn12.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseseriesCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7pCzPcscXJQwdVhqJpvZB8S8EF5sxORc',
    appId: '1:636826174032:ios:89e4557de643e369b08755',
    messagingSenderId: '636826174032',
    projectId: 'fir-series-75010',
    storageBucket: 'fir-series-75010.appspot.com',
    androidClientId: '636826174032-5robrsihrm0p0i5q5g78o7tstnt2hlbj.apps.googleusercontent.com',
    iosClientId: '636826174032-i7qcu64fcd8igdls5rtj83cjeunkgn12.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseseriesCourse',
  );
}
